name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ghcr.io/fvhmifvreed/aldosan_image:latest

      - name: Run Docker container
        run: docker run --rm ghcr.io/fvhmifvreed/aldosan_image:latest

      - name: Run tests inside the container
        run: docker exec aldosan-docker./run-tests.sh
